src/AppBundle/Entity/Item.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Item
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="AppBundle\Entity\ItemRepository")
 */
class Item {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255)
     */
    private $type;

    /**
     * @var float
     *
     * @ORM\Column(name="stock", type="float")
     */
    private $stock;

    /**
     * @var string
     *
     * @ORM\Column(name="stock_type", type="string", length=255)
     */
    private $stockType;

    /**
     * @var string
     *
     * @ORM\Column(name="photo", type="string", length=255,nullable=true)
     */
    private $photo;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Item
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set stock
     *
     * @param float $stock
     * @return Item
     */
    public function setStock($stock)
    {
        $this->stock = $stock;

        return $this;
    }

    /**
     * Get stock
     *
     * @return float 
     */
    public function getStock()
    {
        return $this->stock;
    }

    /**
     * Set stockType
     *
     * @param string $stockType
     * @return Item
     */
    public function setStockType($stockType)
    {
        $this->stockType = $stockType;

        return $this;
    }

    /**
     * Get stockType
     *
     * @return string 
     */
    public function getStockType()
    {
        return $this->stockType;
    }

    /**
     * Set photo
     *
     * @param string $photo
     * @return Item
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * Get photo
     *
     * @return string 
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set type
     *
     * @param string $type
     * @return Item
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string 
     */
    public function getType()
    {
        return $this->type;
    }

    public function getUploadRootDir()
    {
        // absolute path to your directory where images must be saved
        return __DIR__ . '/../../../web/' . $this->getUploadDir();
    }

    public function getUploadDir()
    {
        return 'uploads/items';
    }

    public function getAbsolutePath()
    {
        return null === $this->image ? null : $this->getUploadRootDir() . '/' . $this->image;
    }

    public function getWebPath()
    {
        return null === $this->image ? null : '/' . $this->getUploadDir() . '/' . $this->image;
    }

    public function getImageWebPath()
    {
        return '/' . $this->getUploadDir() . '/' . $this->getPhoto();
    }

}

src/AppBundle/Form/ItemType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ItemType extends AbstractType {

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $myEntity = $builder->getForm()->getData();
        $builder
                ->add('name')
                ->add('type', 'choice', array(
                    'attr' => ['class' => 'iconselector'],
                    'choices' => ['food' => 'Food', 'other' => 'Other', 'office' => 'Office Object']
                ))
                ->add('stock')
                ->add('stockType', 'choice', array(
                    'attr' => ['class' => 'iconselector'],
                    'choices' => ['number' => 'Number', 'gr' => 'Gr', 'kg' => 'Kg', 'm' => 'Meter', 'cm' => 'Centimeter', 'lt' => 'Liter', 'ounce' => 'Ounce']
                ))
                ->add('photo', 'comur_image', array(
                    'uploadConfig' => array(
                        'uploadRoute' => 'comur_api_upload', //optional
                        'uploadUrl' => $myEntity->getUploadRootDir(), // required - see explanation below (you can also put just a dir path)
                        'webDir' => $myEntity->getUploadDir(), // required - see explanation below (you can also put just a dir path)
                        'fileExt' => '*.jpg;*.gif;*.png;*.jpeg', //optional
                        'libraryDir' => null, //optional
                        'libraryRoute' => 'comur_api_image_library', //optional
                        'showLibrary' => true, //optional
                    //  'saveOriginal' => 'originalImage'           //optional
                    ),
                    'cropConfig' => array(
                        'minWidth' => 600,
                        'minHeight' => 600,
                        'aspectRatio' => true, //optional
                        'cropRoute' => 'comur_api_crop', //optional
                        'forceResize' => false, //optional
                        'thumbs' => array(//optional
                            array(
                                'maxWidth' => 200,
                                'maxHeight' => 200
                            ),
                            array(
                                'maxWidth' => 100,
                                'maxHeight' => 100,
                                'useAsFieldImage' => true  //optional
                            )
                        )
                    )
                ))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Item'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'appbundle_item';
    }

}

src/AppBundle/Controller/ItemController.php
<?php

namespace AppBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use AppBundle\Entity\Item;
use AppBundle\Form\ItemType;

/**
 * Item controller.
 *
 * @Route("/admin/item")
 */
class ItemController extends Controller
{

    /**
     * Lists all Item entities.
     *
     * @Route("/", name="admin_item")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('AppBundle:Item')->findAll();

        return array(
            'entities' => $entities,
        );
    }
    /**
     * Creates a new Item entity.
     *
     * @Route("/", name="admin_item_create")
     * @Method("POST")
     * @Template("AppBundle:Item:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new Item();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('admin_item_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Item entity.
     *
     * @param Item $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Item $entity)
    {
        $form = $this->createForm(new ItemType(), $entity, array(
            'action' => $this->generateUrl('admin_item_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Item entity.
     *
     * @Route("/new", name="admin_item_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Item();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a Item entity.
     *
     * @Route("/{id}", name="admin_item_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Item')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Item entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Item entity.
     *
     * @Route("/{id}/edit", name="admin_item_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Item')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Item entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a Item entity.
    *
    * @param Item $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Item $entity)
    {
        $form = $this->createForm(new ItemType(), $entity, array(
            'action' => $this->generateUrl('admin_item_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing Item entity.
     *
     * @Route("/{id}", name="admin_item_update")
     * @Method("PUT")
     * @Template("AppBundle:Item:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Item')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Item entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('admin_item_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a Item entity.
     *
     * @Route("/{id}", name="admin_item_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('AppBundle:Item')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Item entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('admin_item'));
    }

    /**
     * Creates a form to delete a Item entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('admin_item_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm()
        ;
    }
}

src/AppBundle/Resources/views/Item/edit.html.twig
{% extends '::base_admin.html.twig' %}

{% block content -%} 
    <h1>Item edit</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_item') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/AppBundle/Resources/views/Item/index.html.twig
{% extends '::base_admin.html.twig' %}

{% block content -%} 
    <h1>Item list</h1>

    <table class="records_list table">
        <thead>
            <tr>
                <th>Id</th>
                <th>{{"Name"|trans}}</th>
                <th>{{"Stock"|trans}}</th> 
                <th>{{"Photo"|trans}}</th>
                <th>{{"Barcode"|trans}}</th>
                <th>{{"Actions"|trans}}</th>
            </tr>
        </thead>
        <tbody>
            {% for entity in entities %}
                <tr>
                    <td><a href="{{ path('admin_item_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                    <td>{{ entity.name }}</td>
                    <td>{{ entity.stock }} <span title="{{"Stock Type"|trans}}" class="badge">{{ entity.stockType }}</span></td>

                    <td>{% if  entity.photo %}<img src="{{ entity.imageWebPath|thumb(100, 100) }}">{% endif%}</td>
                    <td><div class="thumbnail">{{ barcode({code: ""~entity.id, type: 'ean13', format: 'svg'}) }}</div> </td>
                    <td>

                        <a href="{{ path('admin_item_show', { 'id': entity.id }) }}">show</a>

                        <a href="{{ path('admin_item_edit', { 'id': entity.id }) }}">edit</a>

                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('admin_item_new') }}">
        Create a new entry
    </a>

{% endblock %}

src/AppBundle/Resources/views/Item/new.html.twig
{% extends '::base_admin.html.twig' %}

{% block content -%} 
    <h1>Item creation</h1>

    {{ form(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_item') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock %}

src/AppBundle/Resources/views/Item/show.html.twig
{% extends '::base_admin.html.twig' %}

{% block content -%} 
    <h1>Item  <span class="badge">#{{ entity.id }}</span></h1>

    <table class="record_properties table">
        <tbody>
            <tr>
                <th>Barcode</th>
                <td><div class="thumbnail">{{ barcode({code: ""~entity.id, type: 'ean13', format: 'svg'}) }}</div>  </td>
            </tr>
            <tr>
                <th>{{"Name"|trans}}</th>
                <td>{{ entity.name }}</td>
            </tr>
            <tr>
                <th>{{"Stock"|trans}} : </th>
                <td>{{ entity.stock }}  <span title="{{"Stock Type"|trans}}" class="badge">{{ entity.stockType }}</span></td>
            </tr>

            <tr>
                <th>{{"Photo"|trans}}</th>
                <td><a href="{{entity.imageWebPath}}"><img alt="photo" src="{{entity.imageWebPath}}" width="300"></a></td>
            </tr>
        </tbody>
    </table>
    <div class="hidden-print btn-group">
        <a class="btn btn-default" href="#" onclick="window.print();">
            <i class="fa fa-print"></i> {{"Print"|trans}}
        </a>
        <a href="{{ path('admin_item') }}" class="btn btn-default">
            {{"Back to the list"|trans}}
        </a>
        <a href="{{ path('admin_item_edit', { 'id': entity.id }) }}"  class="btn btn-default">
            <i class="fa fa-edit"></i>  {{"Edit"|trans}}
        </a>
        <hr>
        {{ form(delete_form) }}
    </div>


{% endblock %}